/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#c8c6c5",
        "surface-tint": "#5f5e5e",
        "on-secondary-fixed": "#07006c",
        "on-surface-variant": "#444748",
        "on-primary-container": "#858383",
        "secondary-container": "#6063ee",
        "primary": "#000000",
        "surface-dim": "#dadada",
        "outline-variant": "#c4c7c7",
        "secondary-fixed-dim": "#c0c1ff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed": "#e6e2df",
        "primary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#e1e0ff",
        "surface-bright": "#f9f9f9",
        "outline": "#747878",
        "on-primary-fixed": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        "surface-container-low": "#f3f3f3",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#484645",
        "primary-container": "#1c1b1b",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-fixed-dim": "#cac6c4",
        "error-container": "#ffdad6",
        "secondary": "#4648d4",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed": "#1c1b1a",
        "on-tertiary-container": "#868382",
        "on-background": "#1a1c1c",
        "tertiary-container": "#1c1b1a",
        "on-error": "#ffffff",
        "surface": "#f9f9f9",
        "error": "#ba1a1a",
        "background": "#f9f9f9",
        "surface-container": "#eeeeee",
        "tertiary": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "base": "8px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "display-lg": ["Bebas Neue", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Bebas Neue", "sans-serif"],
        "headline-lg-mobile": ["Bebas Neue", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["80px", {"lineHeight": "80px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "52px", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "headline-lg-mobile": ["36px", {"lineHeight": "40px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
